# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("PkgBenchmark")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'Pkg.add("Documenter"); cd(Pkg.dir("PkgBenchmark")); include(joinpath("docs", "make.jl"))'
